Toolbar headline
rychrr/portfolio_page pull request #1
Opened 2023-03-30 12:28 UTC by rychrr

Good Day ,

The portfolio page was built using HTML/CSS using template 1 from Figma, all files have been updated and a branch created to add the mobile-first headline and toolbar(logo and menu bar)

Regards,

2023-03-30 13:04 UTC, AlphaNtihinduka commented on index.html
> +        </div>
- [ ] We are very close to making our portfolio a pro version. You need to ensure that the list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag). Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href 👍.

2023-03-30 13:09 UTC, AlphaNtihinduka commented on style.css
> +}
- [ ] You should try as much as possible to ensure that the design sticks to the Figma template design. For this case please ensure that the hamburger icon is aligned more to the left such that the `self-desc` text of the section is in line with the icon ☺️.

2023-03-30 13:11 UTC, AlphaNtihinduka commented on style.css
> +}
- [ ] I have noticed that the background image has a margin which is making it have a spacing on the left side. Please ensure that you stick to the Figma design by fixing the image at the start of the portfolio page. This will make your project more professional and user-friendly ☺️.
- [ ] In addition, consider removing the `height` of the main section to ensure that other sections that follow are not affected and preferably consider using padding. This will help you to make your design match the Figma design.
- [ ] Finally, please consider adding the border radius to match the Figma design. If you carefully observe, you will see the border radius at the bottom left of the Figma design

Your design 😎
![image](https://user-images.githubusercontent.com/99394374/228847689-cce77813-cc1a-47c6-b96f-e989398423ef.png)

Figma design 😎 
![border](https://user-images.githubusercontent.com/99394374/228848055-be260332-9e78-482c-9470-649ab0146b7e.png)

2023-03-30 13:20 UTC, AlphaNtihinduka commented on style.css
> +}
- [ ] Please ensure that the width of the heading in `mobile version > 375px` matches the one of Figma design by ensuring that it does not over cross the width of the section. This will make your portfolio more user-friendly ☺️.

2023-03-30 13:21 UTC, AlphaNtihinduka commented on style.css
> +}
- [ ] Please ensure that the width of the description in `mobile version > 375px` matches the one of Figma design by ensuring that it does not over cross the width of the section. This will make your portfolio more user-friendly ☺️.
 
Your design at 375px
![image](https://user-images.githubusercontent.com/99394374/228849249-26731252-f272-41ff-b2a8-64837681dfda.png)

Figma design 😎 
![image](https://user-images.githubusercontent.com/99394374/228849382-09feb795-92bf-4452-8f6d-99ebc51b127a.png)

2023-04-01 18:28 UTC, rychrr commented on index.html
> +       <p class="my_logo"> Richard's Portfolio </p>
Thanks, this is updated

2023-04-01 18:28 UTC, rychrr commented on index.html
> +       <a href="#"><img src="./img/Enabled.png" alt="hamburger_menu" class="hamburger_icon"></a>
Done

2023-04-01 18:28 UTC, rychrr commented
All fixes applied

2023-04-01 19:08 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @rychrr  :wave: 

Well done on implementing the requested changes. :+1:  
While solving the previous problems new issues arise. You need to fix those issues before moving to the next project. :running_man: 

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Linters checks are passing.
✔️ Readme is professional.

## Required Changes ♻️

> Kindly check the comments below.

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 19:08 UTC, Tufahel commented on style.css
> +}
- [ ] Background image should cover the whole body. But here I can see some gaps between the background image and the bodyline. Kindly fix that issue.

- Your Design:
- ![image](https://user-images.githubusercontent.com/60083437/229309611-3dd955a6-9c6d-4f5f-a359-ef05288660b9.png)

- Given Figma Design:
- ![image](https://user-images.githubusercontent.com/60083437/229309646-5ab197ac-02ef-4f5f-97d7-b86b3336769c.png)

2023-04-01 20:15 UTC, rychrr commented on style.css
> +}
THANKS, this is resolved now

2023-04-01 20:15 UTC, rychrr commented
Resolved the background gap issues (see new commits)

2023-04-01 21:05 UTC, souad988 approved these changes
Hi @rychrr , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966](https://user-images.githubusercontent.com/59707859/229313842-45f20031-28b0-4d53-a81e-0acae4cf6a00.gif)


## Highlights
✔Good PR title and description
✔Good communication with reviewers
✔Good efforts
## Optional suggestions
_Please don't forget to remove the logo and microverse title from your README and put instead your projects title .

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 21:31 UTC, merged

2023-04-01 21:31 UTC, rychrr commented
Mobile first set up completed